//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioCard
    {
        public short ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Source { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<short> Interface { get; set; }
        public Nullable<short> AudioChannels { get; set; }
    
        public virtual AudioCardType AudioCardType { get; set; }
        public virtual AudioChannel AudioChannel { get; set; }
        public virtual Interface Interface1 { get; set; }
    }
}
