//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public short ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Source { get; set; }
        public Nullable<short> Place { get; set; }
        public Nullable<short> FormFactor { get; set; }
        public short MBtype { get; set; }
        public Nullable<byte> PowerBlock { get; set; }
        public Nullable<byte> Count525 { get; set; }
        public Nullable<byte> Count35 { get; set; }
        public Nullable<byte> Count25 { get; set; }
        public Nullable<byte> ExpantionSlots { get; set; }
        public Nullable<byte> Fans { get; set; }
        public Nullable<byte> FanPlaces { get; set; }
    
        public virtual CasePlace CasePlace { get; set; }
        public virtual FormFactorsC FormFactorsC { get; set; }
        public virtual FormFactorsMB FormFactorsMB { get; set; }
    }
}
