//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cooler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cooler()
        {
            this.CoolerCompatibilities = new HashSet<CoolerCompatibility>();
        }
    
        public short ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Source { get; set; }
        public short Type { get; set; }
        public string Material { get; set; }
        public Nullable<byte> FanDiameter { get; set; }
        public Nullable<short> FanSpeed { get; set; }
        public Nullable<short> Height { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoolerCompatibility> CoolerCompatibilities { get; set; }
        public virtual CoolerType CoolerType { get; set; }
    }
}
