//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigPC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComponentsPC : DbContext
    {
        public ComponentsPC()
            : base("name=ComponentsPC")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AudioCard> AudioCards { get; set; }
        public virtual DbSet<AudioCardType> AudioCardTypes { get; set; }
        public virtual DbSet<AudioChannel> AudioChannels { get; set; }
        public virtual DbSet<CasePlace> CasePlaces { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Chipset> Chipsets { get; set; }
        public virtual DbSet<CodeName> CodeNames { get; set; }
        public virtual DbSet<CoolerCompatibility> CoolerCompatibilities { get; set; }
        public virtual DbSet<Cooler> Coolers { get; set; }
        public virtual DbSet<CoolerType> CoolerTypes { get; set; }
        public virtual DbSet<DirectXVersion> DirectXVersions { get; set; }
        public virtual DbSet<DriveType> DriveTypes { get; set; }
        public virtual DbSet<FormFactorsC> FormFactorsCs { get; set; }
        public virtual DbSet<FormFactorsD> FormFactorsDs { get; set; }
        public virtual DbSet<FormFactorsHD> FormFactorsHDs { get; set; }
        public virtual DbSet<FormFactorsM> FormFactorsMs { get; set; }
        public virtual DbSet<FormFactorsMB> FormFactorsMBs { get; set; }
        public virtual DbSet<FormFactorsPB> FormFactorsPBs { get; set; }
        public virtual DbSet<GPUModel> GPUModels { get; set; }
        public virtual DbSet<HardDrive> HardDrives { get; set; }
        public virtual DbSet<HDMemoryType> HDMemoryTypes { get; set; }
        public virtual DbSet<Interface> Interfaces { get; set; }
        public virtual DbSet<MemoryType> MemoryTypes { get; set; }
        public virtual DbSet<Motherboard> Motherboards { get; set; }
        public virtual DbSet<OpenGLVersion> OpenGLVersions { get; set; }
        public virtual DbSet<OpticalDrive> OpticalDrives { get; set; }
        public virtual DbSet<PowerBlock> PowerBlocks { get; set; }
        public virtual DbSet<Processor> Processors { get; set; }
        public virtual DbSet<ProcessorSery> ProcessorSeries { get; set; }
        public virtual DbSet<RAM> RAMs { get; set; }
        public virtual DbSet<Socket> Sockets { get; set; }
        public virtual DbSet<SSDDrive> SSDDrives { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Videocard> Videocards { get; set; }
    }
}
