//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboard
    {
        public short ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Source { get; set; }
        public short Socket { get; set; }
        public short FormFactor { get; set; }
        public short Chipset { get; set; }
        public short MemoryType { get; set; }
        public short MemoryFormFactor { get; set; }
        public short MemoryChannels { get; set; }
        public Nullable<int> MaxFrequency { get; set; }
        public Nullable<int> MaxCapacity { get; set; }
        public string AudioChip { get; set; }
        public Nullable<short> AudioChannels { get; set; }
        public byte SATA3 { get; set; }
        public byte M2connector { get; set; }
        public short M2interface { get; set; }
        public byte PCIE1xSlots { get; set; }
        public byte PCIE16xSlots { get; set; }
        public bool PCIE30 { get; set; }
    
        public virtual AudioChannel AudioChannel { get; set; }
        public virtual Chipset Chipset1 { get; set; }
        public virtual FormFactorsM FormFactorsM { get; set; }
        public virtual FormFactorsMB FormFactorsMB { get; set; }
        public virtual Interface Interface { get; set; }
        public virtual MemoryType MemoryType1 { get; set; }
        public virtual Socket Socket1 { get; set; }
    }
}
