//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpticalDrive
    {
        public short ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Source { get; set; }
        public short Type { get; set; }
        public short FormFactor { get; set; }
        public short Interface { get; set; }
    
        public virtual DriveType DriveType { get; set; }
        public virtual FormFactorsD FormFactorsD { get; set; }
        public virtual Interface Interface1 { get; set; }
    }
}
