//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerBlock
    {
        public short ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Source { get; set; }
        public int Power { get; set; }
        public Nullable<short> FormFactor { get; set; }
        public string Sercificate { get; set; }
        public Nullable<byte> SATAPower { get; set; }
        public Nullable<byte> MolexPower { get; set; }
        public Nullable<byte> PCIE8pinPower { get; set; }
    
        public virtual FormFactorsPB FormFactorsPB { get; set; }
    }
}
