//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processor
    {
        public short ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Source { get; set; }
        public Nullable<short> Series { get; set; }
        public Nullable<short> CodeName { get; set; }
        public Nullable<short> Socket { get; set; }
        public Nullable<byte> Cores { get; set; }
        public Nullable<short> CoreFrequency { get; set; }
        public Nullable<short> TurboBoost { get; set; }
        public Nullable<byte> TechProcess { get; set; }
        public Nullable<short> L1 { get; set; }
        public Nullable<short> L2 { get; set; }
        public Nullable<short> L3 { get; set; }
        public Nullable<byte> TDP { get; set; }
        public Nullable<bool> Multiplier { get; set; }
    
        public virtual CodeName CodeName1 { get; set; }
        public virtual ProcessorSery ProcessorSery { get; set; }
        public virtual Socket Socket1 { get; set; }
    }
}
