//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videocard
    {
        public short ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Source { get; set; }
        public short GPUModel { get; set; }
        public byte MemoryCapacity { get; set; }
        public short MemoryType { get; set; }
        public Nullable<short> BusWidth { get; set; }
        public short GPUFrequency { get; set; }
        public short MemoryFrequency { get; set; }
        public Nullable<byte> Techprocess { get; set; }
        public int MaxResolution { get; set; }
        public byte HDMI { get; set; }
        public byte DisplayPort { get; set; }
        public Nullable<short> DirectX { get; set; }
        public Nullable<short> OpenGL { get; set; }
        public byte RecPB { get; set; }
        public byte ExpantionSlots { get; set; }
        public short Length { get; set; }
    
        public virtual DirectXVersion DirectXVersion { get; set; }
        public virtual GPUModel GPUModel1 { get; set; }
        public virtual MemoryType MemoryType1 { get; set; }
        public virtual OpenGLVersion OpenGLVersion { get; set; }
    }
}
